version: '3'

services:
  api:
    container_name: kg-api
    build:
      context: ./kwg-api/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - base_address_http=http://staging.knowwheregraph.org
      - base_address_https=https://staging.knowwheregraph.org
    networks:
      - kwg_network