version: '3'

services:
  kwg-api:
    container_name: kwg-api
    build:
      context: ./kwg-api/
      dockerfile: Dockerfile
    image: kwg-api
    ports:
      - '8080:8080'
    environment:
      - base_address_http=http://kwg-api:8080
      - base_address_https=https://kwg-api:8080
      - base_browse_address=https://stko-kwg.geog.ucsb.edu/browse
    networks:
      - kwg_network
