version: '3'

services:
  kwg-api:
    container_name: kwg-api
    build:
      context: ./kwg-api/
      dockerfile: Dockerfile
    image: kwg-api
    ports:
      - '80:8080'
    environment:
      - base_address_http=https://stko-kwg.geog.ucsb.edu
      - base_address_https=https://stko-kwg.geog.ucsb.edu
