version: '3'

services:
  api:
    container_name: kg-api
    build:
      context: ./kwg-api/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - base_address_http=http://stko-kwg.geog.ucsb.edu
      - base_address_https=https://stko-kwg.geog.ucsb.edu
    networks:
      - kwg_network