version: '3'

services:
  kwg-api:
    container_name: kwg-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - base_address_http=http://staging.knowwheregraph.org
      - base_address_https=https://staging.knowwheregraph.org