version: '3'

services:
  api:
    build: '.'
    ports:
      - '80:80'
    environment:
      - base_address_http=http://staging.knowwheregraph.org
      - base_address_https=https://staging.knowwheregraph.org